const styles = {
  root: { fontFamily: "'DM Sans', sans-serif", background: "#0D0D0F", color: "#E8E8E8", minHeight: "100vh", padding: "20px 20px 40px" },
  loading: { display: "flex", justifyContent: "center", alignItems: "center", height: "100vh", background: "#0D0D0F" },
  spinner: { width: 32, height: 32, border: "2px solid #222", borderTop: "2px solid #4A9B7F", borderRadius: "50%", animation: "spin 1s linear infinite" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 24 },
  title: { fontFamily: "'Space Mono', monospace", fontSize: 26, fontWeight: 700, color: "#fff", letterSpacing: "-0.5px" },
  subtitle: { fontSize: 13, color: "#666", marginTop: 4, letterSpacing: "0.5px" },
  headerRight: { textAlign: "right", display: "flex", alignItems: "center", gap: 12 },
  monthBadge: { fontFamily: "'Space Mono', monospace", fontSize: 12, color: "#888", padding: "6px 12px", border: "1px solid #222", borderRadius: 20, textTransform: "capitalize" },
  tabs: { display: "flex", gap: 4, marginBottom: 20, background: "rgba(255,255,255,.03)", borderRadius: 10, padding: 4 },
  tab: { flex: 1, padding: "10px 16px", border: "none", background: "transparent", color: "#666", fontFamily: "'DM Sans'", fontSize: 13, fontWeight: 500, borderRadius: 8, cursor: "pointer", transition: "all .2s", display: "flex", alignItems: "center", justifyContent: "center" },
  tabActive: { background: "rgba(255,255,255,.08)", color: "#fff" },
  incomeBar: { display: "flex", alignItems: "center", background: "#131316", border: "1px solid #1E1E22", borderRadius: 14, padding: "16px 24px", marginBottom: 20, gap: 24 },
  incomeLeft: { flex: 1 },
  incomeRight: { textAlign: "right" },
  incomeDivider: { width: 1, height: 40, background: "#222" },
  incomeLabel: { display: "block", fontSize: 11, color: "#666", textTransform: "uppercase", letterSpacing: "1px", fontFamily: "'Space Mono'", marginBottom: 6 },
  incomeValue: { fontFamily: "'Space Mono', monospace", fontSize: 22, fontWeight: 700, color: "#fff" },
  incomeInput: { fontFamily: "'Space Mono'", fontSize: 20, background: "transparent", border: "none", borderBottom: "2px solid #4A9B7F", color: "#fff", width: 160, padding: "4px 0" },
  editBtn: { padding: "4px 12px", background: "rgba(255,255,255,.06)", border: "1px solid #333", borderRadius: 6, color: "#888", fontSize: 11, cursor: "pointer", fontFamily: "'DM Sans'", display: "flex", alignItems: "center" },
  smallBtn: { padding: "6px 14px", background: "#4A9B7F", border: "none", borderRadius: 6, color: "#fff", fontSize: 12, cursor: "pointer", fontFamily: "'DM Sans'", fontWeight: 500 },
  content: {},
  grid3: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12, marginBottom: 20 },
  grid2: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 12, marginTop: 16 },
  summaryCard: { background: "#131316", border: "1px solid #1E1E22", borderRadius: 14, padding: 20 },
  iconCircle: { width: 32, height: 32, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center" },
  cardLabel: { fontSize: 11, color: "#666", textTransform: "uppercase", letterSpacing: "1px", fontFamily: "'Space Mono'" },
  cardValue: { display: "block", fontFamily: "'Space Mono', monospace", fontSize: 20, fontWeight: 700 },
  cardSub: { display: "block", fontSize: 12, color: "#555", marginTop: 6, fontFamily: "'DM Sans'" },
  progressSection: { background: "#131316", border: "1px solid #1E1E22", borderRadius: 14, padding: 20, marginBottom: 20 },
  progressBar: { height: 12, background: "#1A1A1E", borderRadius: 6, overflow: "hidden", position: "relative" },
  progressFill: { height: "100%", borderRadius: 6 },
  legend: { fontSize: 11, fontFamily: "'Space Mono'" },
  section: { background: "#131316", border: "1px solid #1E1E22", borderRadius: 14, padding: 20, marginBottom: 20 },
  sectionTitle: { fontFamily: "'Space Mono', monospace", fontSize: 14, fontWeight: 700, color: "#ddd" },
  catRow: { display: "flex", alignItems: "center", padding: "10px 0", borderBottom: "1px solid #1A1A1E" },
  catName: { fontSize: 13, color: "#ccc" },
  catBar: { height: 6, background: "#1A1A1E", borderRadius: 3, overflow: "hidden" },
  catBarFill: { height: "100%", borderRadius: 3 },
  catAmount: { fontFamily: "'Space Mono'", fontSize: 13, fontWeight: 700, minWidth: 100, textAlign: "right" },
  catPct: { fontFamily: "'Space Mono'", fontSize: 11, color: "#555", minWidth: 50, textAlign: "right" },
  empty: { color: "#555", fontSize: 13, padding: "20px 0", textAlign: "center" },
  addBtn: { padding: "10px 20px", background: "#4A9B7F", border: "none", borderRadius: 8, color: "#fff", fontFamily: "'DM Sans'", fontSize: 13, fontWeight: 600, cursor: "pointer", display: "flex", alignItems: "center" },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,.7)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 999, backdropFilter: "blur(4px)" },
  modal: { background: "#18181C", border: "1px solid #2A2A30", borderRadius: 16, padding: 28, width: "100%", maxWidth: 480, maxHeight: "90vh", overflow: "auto" },
  modalTitle: { fontFamily: "'Space Mono'", fontSize: 18, fontWeight: 700, color: "#fff" },
  formGrid: { display: "flex", flexDirection: "column", gap: 16 },
  formGroup: {},
  formLabel: { display: "block", fontSize: 11, color: "#888", textTransform: "uppercase", letterSpacing: "1px", fontFamily: "'Space Mono'", marginBottom: 6 },
  input: { width: "100%", padding: "10px 14px", background: "#0D0D0F", border: "1px solid #2A2A30", borderRadius: 8, color: "#fff", fontFamily: "'DM Sans'", fontSize: 14 },
  categoryGrid: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 6 },
  categoryBtn: { display: "flex", flexDirection: "column", alignItems: "center", gap: 2, padding: "8px 4px", border: "1px solid", borderRadius: 8, background: "transparent", cursor: "pointer", transition: "all .2s" },
  priorityGroup: { display: "flex", gap: 8 },
  priorityBtn: { flex: 1, padding: "8px 12px", border: "1px solid", borderRadius: 8, fontFamily: "'DM Sans'", fontSize: 12, fontWeight: 600, cursor: "pointer", transition: "all .2s" },
  priorityHint: { display: "block", fontSize: 11, color: "#666", marginTop: 6, fontStyle: "italic" },
  formActions: { display: "flex", gap: 12, marginTop: 20, justifyContent: "flex-end" },
  cancelBtn: { padding: "10px 20px", background: "transparent", border: "1px solid #333", borderRadius: 8, color: "#888", fontFamily: "'DM Sans'", fontSize: 13, cursor: "pointer" },
  saveBtn: { padding: "10px 24px", background: "#4A9B7F", border: "none", borderRadius: 8, color: "#fff", fontFamily: "'DM Sans'", fontSize: 13, fontWeight: 600, cursor: "pointer" },
  expenseList: {},
  catHeader: { display: "flex", justifyContent: "space-between", padding: "10px 12px", background: "rgba(255,255,255,.02)", borderRadius: 8, marginBottom: 2, fontSize: 13, fontWeight: 600, color: "#aaa" },
  expenseRow: { display: "flex", alignItems: "center", gap: 12, padding: "10px 12px", borderRadius: 6, transition: "background .15s", cursor: "default" },
  expName: { fontSize: 14, color: "#ddd", marginRight: 8 },
  expAmount: { fontFamily: "'Space Mono'", fontSize: 13, fontWeight: 700, color: "#fff", minWidth: 90, textAlign: "right" },
  priorityTag: { fontSize: 10, padding: "2px 8px", borderRadius: 10, fontWeight: 600, letterSpacing: "0.3px" },
  actionBtn: { background: "none", border: "none", color: "#666", fontSize: 14, cursor: "pointer", padding: "4px 6px", borderRadius: 4, display: "flex", alignItems: "center" },
  insightCard: { display: "flex", gap: 16, alignItems: "flex-start", padding: 20, background: "#131316", border: "1px solid #1E1E22", borderLeft: "3px solid", borderRadius: 14, marginBottom: 20 },
  insightTitle: { fontFamily: "'Space Mono'", fontSize: 13, fontWeight: 700, color: "#ddd", marginBottom: 4 },
  insightText: { fontSize: 13, color: "#999", lineHeight: 1.6 },
  emptyState: { textAlign: "center", padding: "60px 20px" },
  miniCard: { padding: 16, background: "#0D0D0F", borderRadius: 10, border: "1px solid #1E1E22", borderLeft: "3px solid" },
  miniLabel: { display: "block", fontSize: 11, color: "#666", fontFamily: "'Space Mono'", textTransform: "uppercase", letterSpacing: "1px", marginBottom: 6 },
  miniValue: { fontFamily: "'Space Mono'", fontSize: 22, fontWeight: 700 },
  dot: { width: 8, height: 8, borderRadius: "50%", display: "inline-block" },
  oppTitle: { fontSize: 13, fontWeight: 600, color: "#ccc" },
  oppRow: { display: "flex", justifyContent: "space-between", padding: "8px 16px", fontSize: 13, color: "#aaa", borderBottom: "1px solid #1A1A1E" },
  resetBtn: { padding: "8px 20px", background: "transparent", border: "1px solid #333", borderRadius: 8, color: "#666", fontFamily: "'DM Sans'", fontSize: 12, cursor: "pointer", display: "inline-flex", alignItems: "center" },
  logoutBtn: { padding: "6px 12px", background: "transparent", border: "1px solid #333", borderRadius: 6, color: "#888", fontSize: 11, cursor: "pointer", fontFamily: "'DM Sans'", display: "flex", alignItems: "center", gap: 4 },
  monthArrowBtn: { padding: "4px 6px", background: "rgba(255,255,255,.06)", border: "1px solid #333", borderRadius: 6, color: "#888", cursor: "pointer", display: "flex", alignItems: "center" },
  monthTodayBtn: { padding: "4px 10px", background: "rgba(74,155,127,.15)", border: "1px solid rgba(74,155,127,.3)", borderRadius: 6, color: "#4A9B7F", fontSize: 11, fontWeight: 600, cursor: "pointer", fontFamily: "'DM Sans'" },
  historyRow: { display: "flex", alignItems: "center", gap: 16, padding: "14px 16px", background: "rgba(255,255,255,.02)", borderRadius: 10, border: "1px solid #1E1E22" },
};

export default styles;
